# Generated by Django 5.1.4 on 2024-12-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
