# Generated by Django 5.1.4 on 2024-12-10 04:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
